// Runs the exact C02 Code node source the way n8n does (async function body with
// $input, $() and this.helpers) against sample letters, and writes the files to
// ../samples/ for inspection.
//
//   node consult/downloads/tools/test.mjs

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { codeNodeSource } from './build-workflow.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const samples = path.join(root, 'samples');
mkdirSync(samples, { recursive: true });

const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
const codeNode = new AsyncFunction('$input', '$', 'require', codeNodeSource());

async function runCodeNode(row, query = {}, withHelpers = true, req = undefined) {
  const $input = { first: () => ({ json: row }) };
  const $ = (name) => {
    assert.equal(name, 'Download requested');
    return { first: () => ({ json: { params: {}, query } }) };
  };
  const helpers = withHelpers
    ? { prepareBinaryData: async (data, fileName, mimeType) => ({ data, fileName, mimeType }) }
    : {};
  return codeNode.call({ helpers }, $input, $, req);
}

// Leo Marsh (DEMO-1002) doctor letter as generated by C01, with the text exactly as
// stored (single newlines between lines, sign-off on consecutive lines).
const doctorLetter = [
  'Hi Samuel,',
  'Thank you for referring Leo to our office. I wanted to share our clinical findings and the treatment plan we have outlined for him.',
  'Leo presents with a Class I molar relationship bilaterally. His overbite measures 40% and his overjet is 5 mm. In the mandibular arch, there is 3 mm of crowding. We also noted an over-retained mandibular right primary second molar, which will need to be addressed at the outset of treatment.',
  'Our treatment sequence will begin with removal of the lower right primary second molar. Following that, we will bond both the maxillary and mandibular arches and proceed with alignment and leveling. We anticipate the overall treatment time to be in the range of 18 to 24 months.',
  "Please do not hesitate to reach out if you have any questions about Leo's care. We appreciate the referral and look forward to working with him.",
  'Thanks,',
  'Best,',
  'Marc S. Lemchen, DMD',
].join('\n');

// A long family letter (blank lines, curly quotes, dashes, literal "\n") to force a
// second page and exercise the text clean-up.
const para = 'Leo’s upper front teeth sit a little further forward than his lower front teeth — this is very common at his age, and it’s something we’ll guide into a better position as his teeth come in. The lower teeth are slightly crowded, which means there isn’t quite enough room for all of them to line up neatly right now.';
const familyLetter = 'Dear Susan and Nikos,\n\n' +
  Array.from({ length: 9 }, (_, i) => `${i + 1}. ${para}`).join('\n\n') +
  '\\n\\nBest,\nMarc S. Lemchen, DMD';

const cases = [
  { row: { consult_id: 7, output_type: 'doctor_letter', format: 'pdf', letter_text: doctorLetter, letter_date: 'October 6, 2026', first_name: 'Leo', last_name: 'Marsh' }, query: { by: 'LSO@ortheasecurity.com' } },
  { row: { consult_id: 7, output_type: 'doctor_letter', format: 'docx', letter_text: doctorLetter, letter_date: 'October 6, 2026', first_name: 'Leo', last_name: 'Marsh' } },
  { row: { consult_id: 7, output_type: 'family_letter', format: 'pdf', letter_text: familyLetter, letter_date: 'October 6, 2026', first_name: 'Leo', last_name: 'Marsh' } },
  { row: { consult_id: 7, output_type: 'family_letter', format: 'docx', letter_text: familyLetter, letter_date: 'October 6, 2026', first_name: 'Leo', last_name: 'Marsh' } },
];

for (const c of cases) {
  const [item] = await runCodeNode(c.row, c.query);
  const { json, binary } = item;
  assert.equal(json.consult_id, '7');
  assert.equal(json.action, `downloaded ${c.row.output_type} ${c.row.format}`);
  assert.equal(json.actor, c.query ? 'lso@ortheasecurity.com' : 'download link');
  assert.match(json.filename, /^Leo Marsh - (Doctor|Family) Letter\.(pdf|docx)$/);
  assert.equal(binary.data.fileName, json.filename);
  assert.equal(binary.data.mimeType, json.mime);
  const head = binary.data.data.subarray(0, 4).toString('latin1');
  assert.equal(head, c.row.format === 'pdf' ? '%PDF' : 'PK\x03\x04');
  writeFileSync(path.join(samples, json.filename), binary.data.data);
  console.log('ok', json.filename, binary.data.data.length, 'bytes');
}

// Fallback path: no prepareBinaryData, file returned as base64.
{
  const [item] = await runCodeNode(cases[0].row, {}, false);
  const bin = item.binary.data;
  assert.equal(bin.mimeType, 'application/pdf');
  assert.equal(bin.fileExtension, 'pdf');
  assert.equal(Buffer.from(bin.data, 'base64').subarray(0, 4).toString('latin1'), '%PDF');
  console.log('ok base64 fallback');
}

// ---------------------------------------------------------------- composite photo
// Family letter in the live layout (address block, greeting, intro, headings), with
// the composite as JPEG, RGBA PNG and palette PNG. The photo must sit right after
// the first paragraph below the greeting, in both PDF and Word.
{
  const { readFileSync } = await import('node:fs');
  const fx = (f) => readFileSync(path.join(root, 'tools', 'fixtures', f)).toString('base64');
  const owen = [
    'Claire and Mark Bennett', '5874 Woodleigh Drive', 'Carmichael CA', '95834',
    'Dear Claire and Mark,',
    "The following is a brief summary regarding Owen's orthodontic situation. You mentioned that Owen's mother had late eruption of her own teeth and required surgical help to bring in impacted teeth, which helps us understand why Owen's pattern of delayed eruption is something we are watching closely.",
    'Dental Relationships',
    "Owen's upper front teeth sit slightly ahead of his lower front teeth, and there is mild crowding in both arches.",
    'Treatment Plan',
    '• Palatal expander to create space',
    '• Braces on the upper and lower teeth',
    'Fees',
    'The total fee is $6,860, with an initial payment of $860 and 24 monthly payments of $250.',
    'Best,', 'Marc S. Lemchen, DMD',
  ].join('\n');
  const { letterBlocks, withComposite, loadImage } = createRequire(import.meta.url)('../src/render.js');
  const blocks = withComposite(letterBlocks(owen), loadImage(fx('composite.jpg')));
  const at = blocks.findIndex(b => b.kind === 'image');
  assert.equal(blocks[at - 1].kind, 'para');
  assert.match(blocks[at - 1].text, /^The following is a brief summary/);
  assert.equal(blocks[at + 1].text, 'Dental Relationships');
  assert.equal(withComposite(letterBlocks(owen), null).some(b => b.kind === 'image'), false);
  assert.equal(loadImage('bm90IGFuIGltYWdl'), null);              // "not an image" → no photo, letter still built

  for (const [file, label] of [['composite.jpg', 'jpeg'], ['composite-rgba.png', 'rgba'], ['composite-palette.png', 'palette'], ['composite-gray16.png', 'gray16']]) {
    for (const format of ['pdf', 'docx']) {
      const row = { consult_id: 9, output_type: 'family_letter', format, letter_text: owen,
                    letter_date: 'October 9, 2026', first_name: 'Owen', last_name: `Bennett ${label}`,
                    composite_image: fx(file) };
      // As n8n runs it with zlib allowed (NODE_FUNCTION_ALLOW_BUILTIN includes zlib).
      const [{ json, binary }] = await runCodeNode(row, {}, true, createRequire(import.meta.url));
      const buf = binary.data.data;
      const hasPhoto = format === 'pdf' ? buf.toString('latin1').includes('/Im3 7 0 R')
                                        : /word\/media\/composite\.(jpg|png)/.test(buf.toString('latin1'));
      assert.ok(hasPhoto, `photo missing from ${label} ${format}`);
      writeFileSync(path.join(samples, json.filename), buf);
      console.log('ok composite', label, json.filename, buf.length, 'bytes');
    }
  }
  // Without zlib: JPEG still embeds; a PNG that needs decoding is left out of the PDF
  // (the letter is still produced) but stays in the Word file.
  for (const [file, inPdf] of [['composite.jpg', true], ['composite-rgba.png', false]]) {
    const base = { consult_id: 9, output_type: 'family_letter', letter_text: owen, letter_date: 'October 9, 2026',
                   first_name: 'Owen', last_name: 'Bennett', composite_image: fx(file) };
    const [pdf] = await runCodeNode({ ...base, format: 'pdf' });
    assert.equal(pdf.binary.data.data.subarray(0, 4).toString('latin1'), '%PDF');
    assert.equal(pdf.binary.data.data.toString('latin1').includes('/Im3 7 0 R'), inPdf, `no-zlib pdf ${file}`);
    const [docx] = await runCodeNode({ ...base, format: 'docx' });
    assert.ok(/word\/media\/composite\./.test(docx.binary.data.data.toString('latin1')), `no-zlib docx ${file}`);
  }
  console.log('ok without zlib: JPEG in PDF, PNG falls back to Word only');

  // Doctor letters never carry the photo.
  const [{ binary }] = await runCodeNode({ consult_id: 9, output_type: 'doctor_letter', format: 'pdf', letter_text: owen,
    letter_date: 'October 9, 2026', first_name: 'Owen', last_name: 'Bennett', composite_image: fx('composite.jpg') });
  assert.ok(!binary.data.data.toString('latin1').includes('/Im3'), 'doctor letter should have no photo');
  console.log('ok doctor letter has no photo');
}
